version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "POA"
        MIX_ENV: "prod"
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  "./envs/common-blockscout-poa-arianee.env"
    environment:
      SECRET_KEY_BASE: 'test'
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
    ports:
      - 80:4000

